spring.config.import=optional:file:.env[.properties]
spring.application.name=gearwood_puzzle_store

# --- MySQL Database Configuration ---
spring.datasource.url=jdbc:mysql://localhost:3306/puzzle_store
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- JPA + Hibernate Settings ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# --- JWT settings ---
jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXP}

# --- Log settings ---
logging.level.org.springframework.security=INFO
logging.level.root=INFO